name: sticker_manager
description: A local-first cross-platform sticker manager for Windows, macOS and Android.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.1
  crypto: ^3.0.3
  cryptography: ^2.7.0
  file_picker: ^12.3.0
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  path: ^1.9.0
  path_provider: ^2.1.4
  pasteboard: ^0.5.0
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  tray_manager: ^0.2.3
  window_manager: ^0.4.2
  win32: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - windows/runner/resources/app_icon.ico
