import 'dart:io';
import 'dart:typed_data';
import 'package:desktop_drop/desktop_drop.dart';
import 'package:path/path.dart' as path;
import '../services/import_source.dart';
import '../services/media_store.dart';

/// Holds access grants and generated files through preview and confirmation.
class DropImport {
  DropImport(this.items);
  final List<DropItem> items;
  final files = <File>[];
  final _scoped = <Uint8List>[];
  Directory? _temporary;

  Future<void> read({required ImportSource directorySource}) async {
    var materializedBytes = 0;
    for (final item in items) {
      final bookmark = item.extraAppleBookmark;
      if (Platform.isMacOS &&
          bookmark != null &&
          await DesktopDrop.instance
              .startAccessingSecurityScopedResource(bookmark: bookmark)) {
        _scoped.add(bookmark);
      }
      if (item.path.isNotEmpty && path.isAbsolute(item.path)) {
        if (await FileSystemEntity.isDirectory(item.path)) {
          files.addAll(
              await directorySource.scan(Directory(item.path), maxFiles: 1000));
        } else {
          files.add(File(item.path));
        }
      } else if (item.path.isEmpty && item is DropItemFile) {
        final length = await item.length();
        if (length > MediaStore.maxImportFileBytes ||
            length > MediaStore.maxImportTotalBytes - materializedBytes) {
          throw const FormatException('拖入图片超过导入大小限制');
        }
        materializedBytes += length;
        _temporary ??= await Directory.systemTemp.createTemp('sticker-drop-');
        final file = File(path.join(
            _temporary!.path, '${files.length}-${path.basename(item.name)}'));
        await file.writeAsBytes(await item.readAsBytes());
        files.add(file);
      }
    }
  }

  Future<void> dispose() async {
    try {
      if (_temporary != null && await _temporary!.exists()) {
        await _temporary!.delete(recursive: true);
      }
      for (final item in items.where((item) => item.fromPromise)) {
        // Promise paths are generated by the drop plugin, never source files.
        final type = await FileSystemEntity.type(item.path, followLinks: false);
        if (type == FileSystemEntityType.file) await File(item.path).delete();
        if (type == FileSystemEntityType.directory) {
          await Directory(item.path).delete(recursive: true);
        }
      }
    } finally {
      for (final bookmark in _scoped) {
        await DesktopDrop.instance
            .stopAccessingSecurityScopedResource(bookmark: bookmark);
      }
      _scoped.clear();
    }
  }
}
